version: "3"
services:
  postgres:
    image: "postgres:latest"
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./packages/api
    volumes:
      - /app/node_modules
      - ./packages/api:/app
    environment:
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
    depends_on:
      - postgres
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - "80:80"
    depends_on:
      - client
      - admin
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./packages/client
    volumes:
      - /app/.next
      - /app/node_modules
      - ./packages/client:/app
    depends_on:
      - api
  admin:
    build:
      dockerfile: Dockerfile.dev
      context: ./packages/admin
    volumes:
      - /app/.next
      - /app/node_modules
      - ./packages/admin:/app
    depends_on:
      - api
