apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: api
  template:
    metadata:
      labels:
        component: api
    spec:
      containers:
        - name: api
          image: eu.gcr.io/braided-gravity-251515/fantasy-league_api:latest
          ports:
            - containerPort: 3000
          env:
            - name: PGUSER
              value: postgres
            - name: PGHOST
              value: "10.68.224.7"
            - name: PGDATABASE
              value: postgres
            - name: PGPORT
              value: "5432"
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: pgpassword
                  key: PGPASSWORD
            - name: PANDASCOREURL
              value: "https://api.pandascore.co/lol"
            - name: PANDASCOREKEY
              valueFrom:
                secretKeyRef:
                  name: pandascorekey
                  key: PANDASCOREKEY
