apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: rotolol-com-tls
spec:
  secretName: rotolol-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: rotolol.com
  dnsNames:
    - rotolol.com
    - www.rotolol.com
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - rotolol.com
          - www.rotolol.com
